---
title: course checklist
author: Haky Im
date: 2023-03-19
editor:
  markdown:
    wrap: 72
categories:
  - logistics
date-modified: last-modified
---

# course checklist

**three months prior**

- [ ]  identify a TA for the course

**two weeks prior**

- [ ]  update the syllabus (copy the one from the previous year and make necessary changes, new dates, topics, etc)

**one week prior**

- [ ]  download the class roster from facultyaccess page [link](https://facultyaccess.uchicago.edu/selectClass.php)
- [ ]  send welcome email (optional)


- [ ]  check assigned classroom (edit syllabus as needed)
- [ ]  create canvas for the course
follow [link](https://courses.uchicago.edu/faq/) under "how to create an organization site in Canvas" or try direct link [canvas creation link](https://lmsmiddleware.uchicago.edu/org/)
- [ ]  don't forget to publish the canvas
- [ ]  add TA and intructors to canvas
- [ ]  update slack channel
    - [cancer genetics and genomics slack](https://bios25328canc-zp55302.slack.com/admin)

**first week**

- [ ]  create RCC account for students / or posit account
- [ ]  set visibility of canvas to Institution during the first 2 weeks (shopping around period)
    - [ ]  after two week set it to course



---


template email
```{text}
    Dear students, Welcome to the Cancer Genetics and Genomics course (BIOS-25328)! We are Lixing Yang, Haky Im, and Zach Weber and will be walking you through the course. Together, we will explore the current landscape of genetics and genomics of cancer. The field of genomics has made enormous progress over the last two decades, transforming the research of cancer and other diseases. We will survey the state of the art through literature review and hands-on analytical and computational exercises. We hope that by better understanding this devastating disease, we can help push the field forward and enable discoveries for prevention and treatment. In this journey, we will be working together, learning from each other, and supporting one another's success. The homework problems are not presented to you for scoring you but as intergral part of the learning process. If you do not understand what is asked, you are encouraged to ask questions. Our motto is that the only dumb questions are the ones that are not asked. You will get participation credit, regardless of whether your comments are right or not. You can find more detailed in formation in the canvas site ([https://canvas.uchicago.edu/courses/42065](https://canvas.uchicago.edu/courses/42065)) and the linked syllabus. We encourage you to join the slack channel and introduce yourselves. Tell us something fun or boring about yourselves. We look forward to seeing you in class. Lixing Yang, Zach Weber, and Haky Im
    
```
        